### ISSUE TITLE
default values

### ISSUE THREAD

**Issue by rmpestano** [cukespace/arquillian-asciidoctor-extension#3]
About default:

Docktype: here and in maven plugin it is _docbook_, don't you think _html_ is a better default?

HeadAndFooter: we have false and maven plugin [has true](https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/master/src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java#L98) as default

Any other defaults to discuss?

**Comment by rmannibucau** [comment]
Goal was to keep it aligned with mvn plugin - copied them actually. Happy to fix wrongly copied ones, not sure of others.

We can add a "profile" property to switch several of them in with a single property if it helps.

**Comment by rmpestano** [comment]
done [here](https://github.com/cukespace/arquillian-asciidoctor-extension/pull/2/commits/96269cd11409f76fba262f5c72154cada65472af)
